version: '3'

services:
  poa-node:
    build:
      context: ./poa-node
    volumes:
      - ./shared:/root/shared

  public-node:
    build:
      context: ./public-node
    volumes:
      - ./shared:/root/shared
    depends_on:
      - poa-node

  ssh-node:
    build:
      context: ./ssh-node
    volumes:
      - ./shared:/root/shared
    ports:
      - "8022:22"

  tricky:
    build:
      context: ./tricky
    volumes:
      - ./shared:/root/shared
    depends_on:
      - poa-node
    cap_add:
      - SYS_PTRACE

#  babyeth:
#    build:
#      context: ./babyeth
#    volumes:
#      - ./shared:/root/shared
#    depends_on:
#      - poa-node

  faucet:
    build:
      context: ./faucet
    depends_on:
      - public-node

